### ISSUE TITLE
Rollback migrations fail

### ISSUE THREAD

**Issue by mortenscheel** [tobytwigger/laravel-job-status#49]
Rolling back the migrations fail with the following error
```
SQLSTATE[HY000]: General error: 1828 Cannot drop column 'batch_id': needed in a foreign key constraint 'job_status_job_statuses_batch_id_foreign' (SQL: alter table `job_status_job_statuses` drop `batch_id`)
```

So either ignore foreign key checks during rollback, or drop the tables in the right order.

It happens while rolling back the second migration file:
![image](https://user-images.githubusercontent.com/6514342/218457291-dad496ae-8b48-495c-8134-8032e535dabb.png)

**Comment by tobytwigger** [comment]
Thanks a lot for your feedback and pointing out this bug - I've fixed it in #57 and will do a release this evening :)
