### ISSUE TITLE
Unable to send messages using example from docs

### ISSUE THREAD

**Issue by boujois** [tobytwigger/laravel-job-status#50]
**Describe the bug**
In the docs it suggests `$this->line('some message');` however looking at the demo repo it should be `$this->status()->line('some message');`

https://tobytwigger.github.io/laravel-job-status/features/messages/

**To Reproduce**

In your job handle method place:

`$this->line('3/10 emails sent.');`

**Screenshots**
`Call to undefined method App\Jobs\XXXX::line()`

**Additional context**
I might be missing something, as I had issues with vendor:publish, but from looking at the demo repo it looks like a docs issue.

**Comment by shutupflanders** [comment]
Figured it out from the example [repo](https://github.com/tobytwigger/laravel-job-status-demo/blob/main/app/Jobs/BaseJob.php#L63):

You have to chain it like so:
`$this->status()->line('This is a test message.');`
