### ISSUE TITLE
[Documentation] incorrect suggested value for `track_anonymous` ?

### ISSUE THREAD

**Issue by shutupflanders** [tobytwigger/laravel-job-status#51]
After installing this package and publishing the configuration, I was just reading through the docs and noticed a potentially incorrect suggestion for `track_anonymous`:

[https://tobytwigger.github.io/laravel-job-status/enable-tracking/](https://tobytwigger.github.io/laravel-job-status/enable-tracking/)

![image](https://user-images.githubusercontent.com/3372012/218787382-b2163d28-0dba-4041-a6eb-418bd438d2c6.png)

Should this be `true`? as per the configuration docblock:
`By default, we will only track jobs that run that use the 'Trackable' trait.`
`If this is set to true, we will track information about any job with no configuration needed.`

Thanks for putting this together, I'm eager to get it running!

**Comment by shutupflanders** [comment]
Best to put a note about using `true` by the way, I use Laravel Scout in a project with this and it was unable to track the `MakeSearchable` Job, it threw an uncatchable error, if memory serves it was looking for `$jobName` or something

**Comment by tobytwigger** [comment]
Hey @shutupflanders - nice spot! Have just fixed this in #59 .

Thanks again for your contributions and feedback on the documentation - I'm looking forward to getting it running properly too! 

Hopefully we can edit this package to properly handle any errors from third party jobs, but for now I've added a warning as suggested.
